enable-magisk-update = true
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl="https://instagram.en.uptodown.com/android"
patches-source="Aunali321/ReVancedExperiments"
arch="arm64-v8a"
cli-source="inotia00/revanced-cli"
patches-version="dev"
rv-brand="InstagramRevancedExp"
included-patches="'Hide ads' 'Max quality' 'Developer menu'"
