parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = "'Hide ads' 'Video ads' 'Custom branding' 'Change header' 'Miniplayer' 'Bypass image region restrictions' 'Theme' 'Downloads' 'Copy video URL' 'Remove background playback restrictions' 'Bypass URL redirects' 'GmsCore support' 'Announcements' 'Spoof client' 'Check watch history domain name resolution' 'Remove tracking query parameter'"
exclusive-patches = true
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" # fallback
