enable-magisk-update = true
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
version = "latest"
included-patches = "'Hide ads' 'Video ads' 'Copy video URL' 'Downloads' 'Custom branding' 'Change header' 'SponsorBlock' 'Theme' 'Bypass image region restrictions' 'Announcements' 'Remove background playback restrictions' 'Check watch history domain name resolution' 'GmsCore support' 'Bypass URL redirects' 'Remove tracking query parameter' 'Spoof video streams'"
exclusive-patches = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
